document.writeln("<footer id=\'footer\'>");
document.writeln("		<div class=\'row\'>");
document.writeln("			<div class=\'col-lg-12\'>");
document.writeln("				<div style=\'height:40%\'></div>");
document.writeln("				<HR style=\'width:100%\'>");
document.writeln("				<div class=\'float-lg-right\'><a href=\'#\'>Back to top</a></div>");
document.writeln("				");
document.writeln("				<ul class=\'list-unstyled\' style=\'display:flex;flex-direction:row;justify-content:flex-start;\'>");
document.writeln("			        <li style=\'flex-basis:55px;\'><a href=\'#\' onclick=\'pageTracker._link(this.href); return false;\'>Blog</a></li>");
document.writeln("			        <li style=\'flex-basis:55px;\'><a href=\'#\'>RSS</a></li>");
document.writeln("			        <li style=\'flex-basis:75px;\'><a href=\'#\'>Twitter</a></li>");
document.writeln("			        <li style=\'flex-basis:75px;\'><a href=\'#\'>GitHub</a></li>");
document.writeln("			        <li style=\'flex-basis:55px;\'><a href=\'#\'>API</a></li>");
document.writeln("			        <li style=\'flex-basis:55px;\'><a href=\'#\'>Donate</a></li>");
document.writeln("			    </ul>");
document.writeln("			    <ul class=\'list-unstyled\' style=\'display:flex;flex-direction:column;justify-content:flex-start;\'>");
document.writeln("			      <li>Made by <a href=\'#\'>Chunpei Wang</a>.</li>");
document.writeln("			      <li>Code released under the <a href=\'#\'>MIT License</a>.</li>");
document.writeln("			      <li>Based on <a href=\'https://getbootstrap.com/\' rel=\'nofollow\'>Bootstrap</a>. Web fonts from <a href=\'https://fonts.google.com/\' rel=\'nofollow\'>Google</a>.</li>");
document.writeln("				</ul>");
document.writeln("	        </div>");
document.writeln("	    </div>");
document.writeln("	</footer>");